export enum ActionTypes {
  SIGN_IN_START = "SIGN_IN_START",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE = "SIGN_IN_FAILURE",
  CHANGE_AUTHORITIES_START = "CHANGE_AUTHORITIES_START",
  CHANGE_AUTHORITIES_SUCCESS = "CHANGE_AUTHORITIES_SUCCESS",
  CHANGE_AUTHORITIES_FAILURE = "CHANGE_AUTHORITIES_FAILURE",
}
